### ISSUE TITLE
Freighter crates.io name

### ISSUE THREAD

**Issue by Noah-Kennedy** [zhuhaow/dandelion#37]
This project hasn't been touched in several years, and no version of this has ever been published to crates.io.

I'm getting ready to release a private crates registry implementation for general use and I'd like to use the name "freighter".

If you are willing to part with this name, I'd like to be given the `freighter` crate on crates.io, so that I can use it for my project.

**Comment by zhuhaow** [comment]
Hi Noah, do you mind giving me your crate username so I can add you as the owner?

**Comment by Noah-Kennedy** [comment]
Thank you!

`Noah-Kennedy`

**Comment by zhuhaow** [comment]
Done. Feel free to remove me from the owner.

**Comment by Noah-Kennedy** [comment]
Thank you!
